train{
    expname = exp
    dataset_class = data_loader.dataset_pgsr.SceneDatasetDemo
    train_runner_class = run.trainer.PlanarSplatTrainRunner
    max_total_iters = 5000
    coarse_stage_ite = 1000
    split_start_ite = 1000
    plot_freq = 2500
    process_plane_freq_ite = 500
    check_plane_vis_freq_ite = 1000
}
dataset{ 
    dataset_name = PGSR
    tag = PGSR
    init_sphere_radius = 6
    voxel_length = 0.02
    sdf_trunc = 0.08
    depth_trunc = 5.0
    max_depth = 10.0
}
plane_model{
    plane_model_class = net.net_planarSplatting.PlanarSplat_Network
    plane_loss{
        weight_mono_normal = 5.0
        weight_mono_depth = 2.0
    }
    # ==========  training setting
    init_plane_num = 2000
    fix_rot_normal = False
    fix_rot_xy = False
    fix_radii = False
    fix_center = False
    # =========  plane lr
    lr_radii = 0.004
    lr_center = 0.004
    lr_rot_normal = 0.004
    lr_rot_xy = 0.004
    # ==========  plane splatting setting
    RBF_type = rectangle
    RBF_weight_change_type = increase  
    # ==========  plane radii
    radii_dir_type = double  
    radii_init = 0.1
    radii_max_list = [1.0, 1.0]
    radii_min_list = [0.05, 0.05]
    radii_milestone_list = [0, 10000]
    # ========= plane split
    split_thres = 0.20
}
merge_coarse{
    normal_angle_thresh = 15.0
    dist_thresh = 0.1
    mesh_dist_thresh = 0.01
    mesh_dist_thresh_2 = 0.02
    space_resolution = 0.02
    voxel_size = 0.015
    bg_trim_enabled = False
    bg_trim_max_bg_ratio = 0.4
    # ========= fc_shit
    # fc_voxel_size = 0.05
    # find_fc_normal_angle_thresh = 25
    # fc_normal_angle_thresh = 25
    # fc_dist_thresh = 0.2
    # floor_height = -1
    # ceiling_height = -1
}
merge_fine{
    normal_angle_thresh = 5.0
    dist_thresh = 0.05
    mesh_dist_thresh = 0.01
    mesh_dist_thresh_2 = 0.02
    space_resolution = 0.02
    voxel_size = 0.015
    bg_trim_enabled = False
    bg_trim_max_bg_ratio = 0.4
    # ========= fc_shit
    # fc_voxel_size = 0.05
    # find_fc_normal_angle_thresh = 25
    # fc_normal_angle_thresh = 25
    # fc_dist_thresh = 0.2
    # floor_height = -1
    # ceiling_height = -1
}